---
# create-cloud-vm.yml
- name: 'Deploy Cloud-init VMs'
  hosts: "{{ node_vm }}"
  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: node_vm
      prompt: Which node do you want to install?  [h1] [h2] [h3] [h4] [h5] [h6] [h7] [l1] [l2] [l3] [l4]
      private: false
      #default: "1.0"
    - name: name_your_vm
      prompt: What is the VM name?
      private: false
      #default: "1.0"
    - name: ip_vm
      prompt: What will be the IP address of the VM? Example 192.168.0.0/16 - Press Enter for default value. 
      private: false
      default: "192.168.60.61/16"
    - name: resize_vm
      prompt: Enlarge the disk ? Enter for +G | - Press Enter to skip.
      private: false
      default: "0"

  tasks:
  - name: Clone cloud-init clone
    community.general.proxmox_kvm:
      node: "{{ node_vm }}" 
      name: "{{ name_your_vm }}"     
      vmid: 6061
      clone: ubuntu-2204-temp
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ node_vm }}"
      storage: "{{ storage }}"
      timeout: 500

  - name: Change IP
    community.general.proxmox_kvm:
      node: "{{ node_vm }}"      
      name: "{{ name_your_vm }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ node_vm }}"
      net:
        net1: "virtio,bridge=vmbr1"
      ipconfig:
        ipconfig1: "ip={{ ip_vm }},gw={{ ansible_ssh_host }}" #"{{ ansible_ssh_host }}"
      update: true

  - name: Resize the disk 
    community.general.proxmox_disk:
      name: "{{ name_your_vm }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ node_vm }}"
      disk: scsi0
      size: "+{{ resize_vm }}G"
      state: resized    