---
# create-cloud-vm.yml
- name: 'Deploy Cloud-init VMs'

  hosts: "{{ node_vm }}"
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: node_vm
      prompt: Which node do you want to install? [h1][h2]..[l3]
      private: false
      #default: "1.0"
    - name: name_your_vm
      prompt: What is the VM name?
      private: false
      #default: "1.0"
    - name: ip_vm
      prompt: What will be the IP address of the VM? [Just IP is enough]
      private: false
      default: "192.168.60.61"  
    - name: resize_vm
      prompt: Enlarge the disk by? | 0 for skip
      private: false
      default: "0"

  tasks:
  - name: Clone cloud-init clone
    community.general.proxmox_kvm:
      node: "{{ node_vm }}" 
      name: "{{ name_your_vm }}"     
      vmid: 6061
      clone: ubuntu-2204-temp
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ node_vm }}"
      storage: "{{ storage }}"
      #netif: 
       # net1: {"name=eth0,gw=192.168.0.13,ip=192.168.60.182/16,bridge=vmbr1"}
      timeout: 500

  - name: Change IP
    community.general.proxmox_kvm:
      node: "{{ node_vm }}"      
      name: "{{ name_your_vm }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ node_vm }}"
      net:
        net1: "virtio,bridge=vmbr1"
      ipconfig:
        ipconfig1: "ip={{ ip_vm }}/16,gw=192.168.0.13"
      update: true

  - name: Resize the disk 
    community.general.proxmox_disk:
      name: "{{ name_your_vm }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ node_vm }}"
      disk: scsi0
      size: "+{{ resize_vm }}G"
      state: resized    