---
# create-cloud-vm.yml
- name: 'Deploy our Cloud-init VMs'

  hosts: l3
  vars_files:
    - ~/github/ansible/roles/proxmox/vars/main.yml
  tasks:
  - name: Clone cloud-init template
    community.general.proxmox_kvm:
      node: l3
      vmid: 6061
      clone: ubuntu-2204-temp
      name: master-1
      api_user: {{ api_user }}
      api_token_id: {{ api_token_id }}
      api_token_secret: {{ api_token_secret }}
      api_host: {{ l3.api_host }}
      storage: {{ storage }}
      timeout: 500

  - name: Resize the disk 
    community.general.proxmox_disk:
      vmid: 102
      api_user: {{ api_user }}
      api_token_id: {{ api_token_id }}
      api_token_secret: {{ api_token_secret }}
      api_host: {{ l3.api_host }}
      disk: scsi0
      size: +5G
      state: resized
    
  - name: Start VM 
    community.general.proxmox_kvm:
      node: l3
      name: master-1
      api_user: {{ api_user }}
      api_token_id: {{ api_token_id }}
      api_token_secret: {{ api_token_secret }}
      api_host: {{ l3.api_host }}
      state: started
      timeout: 500
      