---
# create-cloud-vm.yml
- name: 'Deploy our Cloud-init VMs'

  hosts: "{{ node }}"
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: node
      prompt: Which node do you want to install? [h1][l3]
      private: false
      #default: "1.0"
    - name: name_your_vm
      prompt: What is the VM name?
      private: false
      #default: "1.0"
    - name: resize_vm
      prompt: Enlarge the disk by? | 0 for skip
      private: false
      default: "0"

  tasks:
  - name: Clone cloud-init template
    community.general.proxmox_kvm:
      node: "{{ node }}"
      clone: ubuntu-2204-temp
      name: "{{ name_your_vm }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ node }}"
      storage: "{{ storage }}"
      timeout: 500


    
  - name: Start VM 
    community.general.proxmox_kvm:
      node: "{{ node }}"
      name: "{{ name_your_vm }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ l3.api_host }}"
      state: started
      timeout: 500
      