---
# create-cloud-vm.yml

- name: 'Deploy our Cloud-init VMs'

  hosts: l3

  tasks:
  - name: Clone cloud-init template
    community.general.proxmox_kvm:
      node: l3
      vmid: 6061
      clone: ubuntu-2204-temp
      name: master-1
      api_user: ansible@pam
      api_token_id: ansible_pve_token
      api_token_secret: 6dd56423-3c6f-4ec1-99d2-a882945c865b
      api_host: 192.168.0.13
      storage: local-lvm
      timeout: 500

  - name: Resize the disk 
    community.general.proxmox_disk:
      vmid: 102
      api_user: ansible@pam
      api_token_id: ansible_pve_token
      api_token_secret: 6dd56423-3c6f-4ec1-99d2-a882945c865b
      api_host: 192.168.0.13
      disk: scsi0
      size: +5G
      state: resized
    
  - name: Start VM 
    community.general.proxmox_kvm:
      node: l3
      name: master-1
      api_user: ansible@pam
      api_token_id: ansible_pve_token
      api_token_secret: 6dd56423-3c6f-4ec1-99d2-a882945c865b
      api_password:
      api_host: 192.168.0.13
      state: started
      timeout: 500
      