---
- name: 'Deploy our Cloud-init VMs'
  hosts: "{{ node_vm }}"
  vars_files:
    - vars/main.yml
  tasks:

  - name: Clone cloud-init template
    community.general.proxmox_kvm:
      node: "{{ node_vm }}"
      clone: ubuntu-2204-temp
      name: "{{ name_your_vm }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ node }}"
      storage: "{{ storage }}"
      timeout: 500