  - name: Resize the disk 
    community.general.proxmox_disk:
      name: "{{ name_your_vm }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ {{ node }}.api_host }}"
      disk: scsi0
      size: "+{{ resize_vm }}G"
      state: resized